config/routes.rb
Rails.application.routes.draw do

  resources :images
  resources :carrierwave_images
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :businesses
  resources :articles
  resources :players
  resources :industries

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  has_secure_password

  has_and_belongs_to_many :businesses
  has_many :articles, through: :businesses
  has_many :industries, through: :businesses
  has_many :players, through: :businesses

end

app/controllers/businesses_controller.rb
require 'pry'
class BusinessesController < ApplicationController
  before_action :set_business, only: [:show, :edit, :update, :destroy]

  # GET /businesses
  # GET /businesses.json
  def index
    @businesses = Business.all
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
  end

  # GET /businesses/new
  def new
    @business = Business.new
  end

  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(business_params)
    set_associations

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update

    @business = Business.find(params[:id])
    set_associations

    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url, notice: 'Business was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_associations
      @business = Business.find(params[:id])
      industriesParams = params[:business][:industry_ids].reject{ |c| c.empty? }
      playerParams = params[:business][:player_ids].reject { |c| c.empty? }
      articleParams = params[:business][:article_ids].reject { |c| c.empty? }
      @business.update(:player_ids => playerParams, :industry_ids => industriesParams, :article_ids => articleParams)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
      params.fetch(:business).permit(:name, :description, :location, :dropbox, :website, :logo, :industry_ids)
    end



end

app/helpers/business_helper.rb
module BusinessHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<div class="row mt-3">
  <div class="col-md-1"></div>
  <div class="col-md-7 table-background">
    <%= form_for(business) do |f| %>
    <% if business.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(business.errors.count, "error") %> prohibited this business from being saved:</h2>
        <ul>
        <% business.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

        <div class="field form-group row">
          <%= f.label :name, class:"col-sm-3" %>
          <%= f.text_field :name %>
        </div>
        <div class="field form-group row">
          <%= f.label :description, class:"col-sm-3"%>
          <%= f.text_field :description %>
        </div>
        <div class="field form-group row">
          <%= f.label :location, class:"col-sm-3"%>
          <%= f.text_field :location %>
        </div>
        <div class="field form-group row">
          <%= f.label :dropbox, class:"col-sm-3"%>
          <%= f.text_field :dropbox %>
        </div>
        <div class="field form-group row">
          <%= f.label :website, class:"col-sm-3"%>
          <%= f.text_field :website %>
        </div>
        <div class="field form-group row">
          <%= f.label :logo, class:"col-sm-3"%>
          <%= f.text_field :logo %>
        </div>
        <div class="field form-group row">
          <%= f.label :industry_ids, "Industries", class:"col-sm-3"%>
          <%= f.collection_check_boxes( :industry_ids, Industry.all, :id, :name) %>
        </div>
        <div class="field form-group row">
          <%= f.label :player_ids, "Players", class:"col-sm-3"%>
          <%= f.collection_check_boxes( :player_ids, Player.all, :id, :name) %>
        </div>
        <div class="field form-group row">
          <%= f.label :article_ids, "Players", class:"col-sm-3"%>
          <%= f.collection_check_boxes( :article_ids, Article.all, :id, :name) %>
        </div>
        <div class="field form-group row">
          <%= f.submit %>
        </div>

    <% end %>
  </div>
</div>

app/views/businesses/edit.html.erb
<div class="row">
  <div class="col-md-10 mb-3 mt-3 ml-5">
    <h3>Edit Business</h3>
    <h3 class="background-bar">Edit Business</h3>
    </div>
  </div>

<%= render 'form', business: @business %>

app/views/businesses/index.html.erb
<div class="container">

  <p id="notice"><%= notice %></p>

    <div class="row marginBottom30">
      <div class="col-md-10">
        <h3>Businesses</h3>
        <h3 class="background-bar">Businesses</h3>
      </div>

      <div class="col-md-2 mt-2">
        <%= link_to "New Business", new_business_path %>
      </div>
    </div>

<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10 table-background">
      <table class="table">
        <thead class="" style="background-color: darkgrey">
          <tr style="height:40px;">
            <th><h6>Name</h6></th>
            <th><h6>Description</h6></th>
            <th><h6>Location</h6></th>
            <th><h6>Dropbox</h6></th>
            <th><h6>Website</h6></th>
            <th><h6>Logo</h6></th>
            <th><h6>Industry</h6></th>
            <th><h6>Articles</h6></th>
            <th><h6>Players</h6></th>
          </tr>
        </thead>
        <tbody>

        <% @businesses.each do |business| %>
          <tr style="height:40px;padding:0;">
              <td class="company-name"><%= link_to business.name, business_path(business) %></td>
              <td><%= business.description %></td>
              <td><%= business.location %></td>
              <td><a href="<%= business.dropbox %>">Link</a></td>
              <td><a href='<%= business.website %>'>Link</a></td>
              <td><%= business.logo %></td>
              <td><%= render partial: 'components/list', locals: {collection: business.industries} %></td>
              <td><%= render partial: 'components/list', locals: {collection: business.articles} %></td>
              <td><%= render partial: 'components/list', locals: {collection: business.players} %></td>
            </tr>
        <% end %>
        </tbody>
      </table>

  </div>

</div>
</div>

app/views/businesses/new.html.erb
<div class="container">

  <div class="row">

    <div class="col-md-10 col-md-offset-1 marginBottom30">
      <h3>New Business</h3>
      <h3 class="background-bar">New Business</h3>
      </div>
    </div>

  <%= render 'form', business: @business %>
</div>

app/views/businesses/show.html.erb
<div class="container">

  <p id="notice"><%= notice %></p>

    <div class="row mb-3 mt-3">
      <div class="col-md-1">

        <% if @business.logo.present? %>
        <div class="image-filler">
          <%= image_tag @business.logo.url(:thumb) %>
        </div>
        <% else %>
          <div class="image-filler"></div>
        <% end %>

      </div>
      <div class="col-md-9">

            <h3 class="startup-name"><%= @business.name %></h3>
            <h3 class="background-bar-show"><%= @business.name %></h3>

      </div>
    </div>

  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10 table-background">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Location</th>
          <th>Dropbox</th>
          <th>Website</th>
          <th>Industry</th>
          <th>People</th>
          <th>Articles</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= link_to @business.name, business_path(@business) %></td>
          <td><%= @business.description %></td>
          <td><%= @business.location %></td>
          <td><a href="<%= @business.dropbox %>">Link</a></td>
          <td><a href='<%= @business.website %>'>Link</a></td>
          <td><%= render partial: 'components/list', locals: {collection: @business.industries} %></td>
          <td><%= render partial: 'components/list', locals: {collection: @business.players} %></td>
          <td><%= render partial: 'components/list', locals: {collection: @business.articles} %></td>
         </tr>
        </tbody>
      </table>
      <%= link_to "Edit", edit_business_path(@business) %> |
      <%= link_to "Delete", @business, method: :delete %> |
      <%= link_to "Add New Article", new_article_path(startup: @business.name) %>
     </div>
    </div>
</div>