config/routes.rb
Rails.application.routes.draw do

  resources :images
  resources :carrierwave_images
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :businesses
  resources :articles
  resources :players
  resources :industries

end

app/models/industry.rb
class Industry < ApplicationRecord

  has_and_belongs_to_many :businesses
  has_and_belongs_to_many :articles
  has_and_belongs_to_many :players
  has_many :images, as: :item, dependant: :destroy
end

app/controllers/industries_controller.rb
class IndustriesController < ApplicationController
  before_action :set_industry, only: [:show, :edit, :update, :destroy]

  # GET /industries
  # GET /industries.json
  def index
    @industries = Industry.all
  end

  # GET /industries/1
  # GET /industries/1.json
  def show
  end

  # GET /industries/new
  def new
    @industry = Industry.new
  end

  # GET /industries/1/edit
  def edit
  end

  # POST /industries
  # POST /industries.json
  def create
    @industry = Industry.new(industry_params)

    respond_to do |format|
      if @industry.save
        format.html { redirect_to @industry, notice: 'Industry was successfully created.' }
        format.json { render :show, status: :created, location: @industry }
      else
        format.html { render :new }
        format.json { render json: @industry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /industries/1
  # PATCH/PUT /industries/1.json
  def update
    respond_to do |format|
      if @industry.update(industry_params)
        format.html { redirect_to @industry, notice: 'Industry was successfully updated.' }
        format.json { render :show, status: :ok, location: @industry }
      else
        format.html { render :edit }
        format.json { render json: @industry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /industries/1
  # DELETE /industries/1.json
  def destroy
    @industry.destroy
    respond_to do |format|
      format.html { redirect_to industries_url, notice: 'Industry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_industry
      @industry = Industry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def industry_params
      params.fetch(:industry).permit(:name)
    end
end

app/helpers/industries_helper.rb
module IndustriesHelper
end

app/views/industries/_form.html.erb
<div class="row mt-3">
  <div class="col-md-1"></div>
  <div class="col-md-7 table-background">

    <%= form_for [industry], html: { multipart: true } do |f| %>

        <% if industry.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(industry.errors.count, "error") %> prohibited this industry from being saved:</h2>

            <ul>
            <% industry.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="field form-group row">
          <%= f.label :name, class:"col-sm-3" %>
          <%= f.text_field :name %>
        </div>
        <div class="field form-group row">
          <%= f.submit %>
        </div>

    <% end %>

  </div>
</div>

app/views/industries/edit.html.erb
<div class="row">
  <div class="col-md-10 mb-3 mt-3 ml-5">
    <h3>Edit Industry</h3>
    <h3 class="background-bar">Edit Industry</h3>
    </div>
  </div>

<%= render 'form', industry: @industry %>

app/views/industries/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
    <div class="row mb-3 mt-3">
      <div class="col-md-10">
        <h3>Industries</h3>
        <h3 class="background-bar">Industries</h3>
      </div>

      <div class="col-md-2 mt-2">
        <%= link_to "New Industry", new_industry_path %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-1"></div>
      <div class="col-md-10 table-background">

        <table class="table">
          <thead>
            <tr>
              <th style='width:200px'>Name</th>
              <th>Businesses</th>
              <th>Players</th>
              <th>Articles</th>
            </tr>
          </thead>
          <tbody>

          <% @industries.each do |industry| %>
          <tr>
              <td style='width:200px'><%= link_to industry.name, industry %></td>
              <td><%= render partial: 'components/list', locals: {collection: industry.businesses} %></td>
              <td><%= render partial: 'components/list', locals: {collection: industry.players} %></td>
              <td><%= render partial: 'components/list', locals: {collection: industry.articles} %></td>
            </tr>
          <% end %>
          </tbody>
        </table>

      </div>

    </div>
    </div>

app/views/industries/new.html.erb
<div class="row">
  <div class="col-md-10 mb-3 mt-3 ml-5">
    <h3>New Industry</h3>
    <h3 class="background-bar">New Industry</h3>
    </div>
  </div>

<%= render 'form', industry: @industry %>

app/views/industries/show.html.erb
<div class="container">

    <p id="notice"><%= notice %></p>

    <div class="row mb-3 mt-3">
      <div class="col-md-10">
        <h3><%= @industry.name %></h3>
        <h3 class="background-bar"><%= @industry.name %></h3>
      </div>
    </div>

    <div class="row">
      <div class="col-md-1"></div>
      <div class="col-md-10 table-background">
        <table class="table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Businesses</th>
              <th>Articles</th>
              <th>Players</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @industry.name %></td>
              <td><%= render partial: 'components/list', locals: {collection: @industry.businesses} %></td>
              <td><%= render partial: 'components/list', locals: {collection: @industry.players} %></td>
              <td><%= render partial: 'components/list', locals: {collection: @industry.articles} %></td>
            </tr>
          </tbody>
        </table>

        <%= link_to "Edit", edit_industry_path(@industry) %> |
        <%= link_to "Delete", @industry, method: :delete %>

      </div>

    </div>
    </div>